# Machine Learning (Spring 2022)
### Numpy 101

In [5]:
import numpy as np

Reference: https://cs231n.github.io/python-numpy-tutorial/#arrays

## Initialize Arrays

In [6]:
a = [1, 2, 3]

In [7]:
type(a)

list

In [9]:
a = np.array([1, 2, 3])
type(a)

numpy.ndarray

In [10]:
a.shape

(3,)

In [11]:
a[2]

3

In [12]:
a[2] = 5

In [13]:
a

array([1, 2, 5])

In [14]:
b = np.array([[1,2,3],[4,5,6]]) 

In [15]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
b.shape

(2, 3)

In [17]:
b[0, 0]

1

In [18]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
np.full((2, 2), 42)

array([[42, 42],
       [42, 42]])

In [ ]:
np.arange(12)

In [ ]:
np.random.random((2,2))

## Array types

In [ ]:
a = np.zeros((2, 3))
a

In [ ]:
a.dtype

In [ ]:
a = np.zeros((2, 3), dtype=int)
a

In [ ]:
a.dtype

In [ ]:
a = np.array([2, 3, 5])

In [ ]:
a.dtype

In [ ]:
a = np.array(["hello", "world"])  # uncommon usage
a

## Array Indexing

In [ ]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [ ]:
a

In [ ]:
a[:, :2]

In [ ]:
a[:, :2] = 6

In [ ]:
a

In [ ]:
a[[0, 1, 2], [0, 1, 2]]

In [ ]:
y = np.array([0, 1, 0, 0, 1, 1, 1, 0, 0])
x = np.arange(y.shape[0])

In [ ]:
x

In [ ]:
y > 0

In [ ]:
y[y > 0]

In [ ]:
x[y > 0]

## Array math

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [ ]:
x

In [ ]:
y

In [ ]:
x * y

In [ ]:
np.sqrt(x)

In [ ]:
x.T

In [ ]:
a = np.array([1, 2, 3])
a

In [ ]:
np.dot(a, a)    #  a.dot(a)

In [ ]:
np.sum(a)    # a.sum()

## Broadcasting

In [ ]:
x

In [ ]:
x + 2

In [ ]:
x + np.array([0, 10])

In [ ]:
i = np.zeros((3, 1, 5))
j = np.zeros((1, 2, 5))

In [ ]:
(i + j).shape

In [ ]:
i = np.zeros((3, 1, 5))
j = np.zeros((2, 2, 5))

In [ ]:
(i + j).shape

In [ ]:
a = np.array([[1, 2, 3]])
a.shape

In [ ]:
b = np.broadcast_to(a, (4, 3))
b.shape

In [ ]:
b

## Reshaping & Combination

In [ ]:
a = np.arange(12)
a

In [ ]:
a.reshape((3, 4))

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
np.concatenate([a, b])

In [ ]:
np.stack([a, b], axis = 0)

In [ ]:
np.stack([a, b], axis = 1)

In [ ]:
a = np.array([1, 2, 3])
a

In [ ]:
np.repeat(a, 4, axis=0)

## Plotting

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
x = np.array([1, 2, 3, 4])
y = np.array([2, 6, 8, 7])
y

In [ ]:
plt.plot(x, y)
plt.show()

In [ ]:
plt.bar(x, y)
plt.show()

In [ ]:
z = np.array([3, 5, 7, 6])
plt.plot(x, y, label='plot of y')
plt.plot(x, z, label='plot of z')
plt.legend()
plt.show()

## Quiz

1. Create an array of squared numbers up to 100 [1, 4, 9, ..., 100] using numpy

2. Given a probability distribution p, find its mean (expectation)

In [ ]:
x = np.array([1, 2, 3, 4])
px = np.array([0.5, 0.25, 0.15, 0.1])

3. Given 2 vectors $\mathbf{a}$ and $\mathbf{b}$, create a matrix $\mathbf{M}$ whose entry $M_{ij}=a_i+b_j$

In [ ]:
a = np.array([20, 40, 60, 90])
b = np.array([1, 2, 3, 5, 7])
n, = a.shape
m, = b.shape

## Numpy Documentation

https://numpy.org/doc/stable/reference/